### ISSUE TITLE
Provable support in RSK Testnet

### ISSUE THREAD

**Issue by aeidelman** [oraclize/rsk-api#2]
It would be super useful for us to have Provable SC's deployed in RSK Testnet. They have not been deployed after RSK Testnet was reset a few weeks ago.

**Comment by gskapka** [comment]
@aidelman - you're quite right and the situation has been rectified now. You'll find the Provable contracts deployed on the test-net and the API in this repo updated with those contract's addresses accordingly.

Closing due to aforementioned, but do let us know if you have any further issues!

**Comment by aeidelman** [comment]
Thank you @gskapka ! We'll test it asap and let you know if we have issues.
